### ISSUE TITLE
Cerise theme ( not acp ) .. SCEditor sizing problem

### ISSUE THREAD

**Issue by oneduality** [vintagedaddyo/MyBB_Theme_Cerise#1]
When I switch to the default MyBB template the sceditor is fine.. 

When I use Cerise, which I love.. the editor is still messed up.

Basically the sceditor is just showing a line or two at the top, the editor won't expand to the full size of the textarea.  But like I said it works fine on the default..

I've had this issue since 1821 when I first installed MyBB and the theme.. today I updated to the latest version of the theme and the latest version of MyBB just to see if the issue would go away but it didn't :(

![messed-up](https://user-images.githubusercontent.com/3308908/96934612-7ffc0100-1490-11eb-8874-4ac83821b295.jpg)

**Comment by vintagedaddyo** [comment]
That images shows that it is not the latest version, as I removed
buttons-dark editor theme after 1822 starting with 1823 due to changes in the editor in 1821/1822 and the
editor theme for cerise in latest version (for 1824):
https://github.com/vintagedaddyo/MyBB_Theme_Cerise is not called
"buttons-dark" anymore but is called "cerise" and is different using font
awesome 4 icons (similar to the font awesome 5 tutorial I once shared for 1.8.21 ( https://github.com/vintagedaddyo/MyBB_Theme_Mybb-Font-Awesome-5-light-dark-SCEditor-  variants of such found used in fa5 themes https://github.com/vintagedaddyo/MyBB_Theme_FA5 &  https://github.com/vintagedaddyo/MyBB_Theme_FA5Dark ) , so if you have buttons-dark editor theme enabled that
either means you are using and older version of cerise or enabled the no
longer used buttons-dark editor theme in new theme?

Old theme version example:

<editortheme><![CDATA[buttons-dark.css]]></editortheme>

New theme version example:

<editortheme><![CDATA[Cerise.css]]></editortheme>

Newest theme .xml for example:

https://github.com/vintagedaddyo/MyBB_Theme_Cerise/blob/master/Cerise-theme.xml

 Newest editortheme for example:

https://github.com/vintagedaddyo/MyBB_Theme_Cerise/blob/master/Upload/jscripts/sceditor/themes/Cerise.css

https://github.com/vintagedaddyo/MyBB_Theme_Cerise/blob/master/Upload/jscripts/sceditor/styles/jquery.sceditor.Cerise.css


Notice how the editor theme call is diff in those examples pulled from older and then lastly the newest theme .xml file? 

Note: as I ceased most of my mybb dev work awhile ago, I am not sure if and or when I may or may not choose and or have free time to update the old now removed buttons-dark editor theme as it is no longer used by this theme

**Comment by oneduality** [comment]
I downloaded it literally just today today and overwrote what was in there.. not sure what to do.. but it's had this issue for a long time.. any suggestions? 

I can try changing the buttons theme but all I can say is that I did download the newest  cerise as of today ( 10/22/2020 )

**Comment by vintagedaddyo** [comment]
Here is a screenshot of  quick test of quickly installing a localhost, mybb, and the latest cerise theme on my tablet as I am currently without a laptop or desktop. https://ibb.co/vDXhgZt as you can see the editor theme is different than your screen preview ie: your screen has buttons-dark.css active as in pre-1.8.23 version of cerise and my preview has cerise.css active as the latest version has by default now.

**Comment by oneduality** [comment]
I believe you, trust me .. what I'm saying is do you have any suggestion on how to get this situated? I love the theme.. I did overwrite the files today while updating mybb at the same time.. I downloaded a zip from your repo's code button

I don't know why it's behaving that way.. so just seeking help if possible, not sure if maybe deleting the cache/themes folder would be suggested.. or deleting the theme outright and re-uploading it from scratch? I haven't customized it outside of the logo

**Comment by oneduality** [comment]
Fixed... I deleted the old folder outright... uploaded it again and set the buttons to cerise.. now it's behaving :) 

So sorry for bothering you .. the site I'm running it on is onedualityfakes.com .. I really love the work!

**Comment by vintagedaddyo** [comment]
first thing make sure in theme settings the latest theme has the correct editor theme selected ie cerise.css then also make sure to look into your user setting to make sure you do not have buttons-dark selected, clear browser history cache and see if that sorts it...., if not then manually go into your forum root directory upload/jscripts/sceditor/styles/ and look for "jquery.sceditor.buttons-dark.css" and delete it and then look into upload/jscripts/sceditor/themes/ and look for "buttons-dark.css" and delete it, clear browser and see if that sorts your issue?

**Comment by vintagedaddyo** [comment]
nice, cool beans to reading just now that you got it sorted out. Thanks, best of luck and enjoy. Will mark issue closed.
